---
- hosts: todos
  user: centos
  become: yes
  roles:
   - docker

- hosts: rootCA
  user: centos
  #become: yes
  roles:
   - CA
   - bootstrap-CA 

- hosts: FabricCA
  user: centos
  become: yes
  roles:
    - CA
    - bootstrap-CA

- hosts: peers
  user: centos
  become: yes
  roles:
    - peer

- hosts: orderers
  user: centos
  become: yes
  roles:
   - orderer
