#- name: "Instalo dnf-plugins-core"
#  environment: "{{ proxy_env }}"
#  yum:
#    name: "{{ item }}"
#  with_items: 
#    - yum-utils
#    - device-mapper-persistent-data
#    - lvm2


- name: "Instalo Docker Repo"
  environment: "{{ proxy_env }}"
  yum_repository:
   name: docker-repo
   description: docker-repo
   description: Docker CE Stable - $basearch
   baseurl: https://download.docker.com/linux/centos/7/$basearch/stable
   enabled: 1
   gpgcheck: 1
   gpgkey: https://download.docker.com/linux/centos/gpg
  register: first_time

- name: "Instalo Docker"
  environment: "{{ proxy_env }}"
  yum: name="docker-ce-17.06.1.ce" state=present update_cache=yes

- name: "Instalo Docker Compose"
  environment: "{{ proxy_env }}"
  command: "curl -L https://github.com/docker/compose/releases/download/1.16.1/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose"
  when: first_time.changed

- name: "Configuro Docker Compose"
  environment: "{{ proxy_env }}"
  command: "chmod +x /usr/local/bin/docker-compose"
  when: first_time.changed
  
